def get_python_version() -> str: ...

class ShelvedCache:
    def __init__(self, path) -> Any: ...
    def get_cache(self) -> Any: ...
    def items(self) -> Any: ...
    def clear(self) -> Any: ...

class DefaultShelveCache:
    def __init__(self, f, path) -> Any: ...

