class IAutoData:
    def value(self) -> Any: ...
    def format(self) -> Any: ...
    def to(self, format) -> Any: ...
    def convert(self, format) -> 'IAutoData': ...
    def converter(self, format) -> Converter: ...
    def map(self, f, format = ...) -> 'IAutoData': ...
    def override(self, rule: 'AutoRuleBook') -> 'IAutoData': ...
    def cast(self, new_format) -> 'IAutoData': ...

